url: "https://esmoore.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Eric S. Moore" # the name of your site, e.g. ACME Corp.
description: "Ink and Isomorphism"
author: Eric S. Moore
#email: email@email.com
#description: 

permalink: /:categories/:year/:month/:day/:title:output_ext

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
  lowercase_titles: false # show titles in lowercase in lists