url: "https://esmoore.com" # the base hostname & protocol for your site, e.g. http://example.com
title: "Eric S. Moore" # the name of your site, e.g. ACME Corp.
description: "Historical Penmanship, Mathematics, Philosophy"
author: Eric S. Moore
#email: email@email.com
#description: 

permalink: /:categories/:year/:month/:day/:title:output_ext

theme_config:
  back_home_text: "<<<" # customize text for homepage link in post layout
  date_format: "%Y.%m.%d" # customize how date is formatted
  show_description: true # show blog description in home page
  lowercase_titles: false # show titles in lowercase in lists
