baseURL = 'https://esmoore.com/'
languageCode = 'en-us'
title = 'Eric S. Moore'

disableKinds = ["sitemap"]

ignoreLogs = ['warning-goldmark-raw-html']

[markup.goldmark.renderer]
unsafe= true

[markup.goldmark.extensions]
typographer = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[security.funcs]
  getenv = ['^HUGO_', '^CI$', '^CF_PAGES_']

